name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        env:
          privateKey: ${{ secrets.GCP_PUBSUB_PRIVATE_KEY }}
          clientEmail: ${{ secrets.GCP_PUBSUB_CLIENT_EMAIL }}
          projectID: ${{ secrets.GCP_PUBSUB_PROJECT_ID }}
          subscriptionID: ${{ secrets.GCP_PUBSUB_SUBSCRIPTION_ID }}
          topicID: ${{ secrets.GCP_PUBSUB_TOPIC_ID }}
          batchSize: ${{ secrets.GCP_PUBSUB_BATCH_SIZE }}
          batchDelay: ${{ secrets.GCP_PUBSUB_BATCH_DELAY }}
        run: make test GOTEST_FLAGS="-v -count=1"
